services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Teste123@"
    volumes:
      - task:/var/opt/mssql
    networks:
      app-network:
        aliases:
          - sql

  task-api:
    build:
      context: ./TaskAPI/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5125:8080"
    depends_on:
      - database
    networks:
      - app-network

  task-ui:
    build:
      context: ./TaskUI
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - task-api

volumes:
  task:

networks:
  app-network:
    driver: bridge